### ISSUE TITLE
Remove '-d' option from dockerComposeUp command

### ISSUE THREAD

**Issue by renanwilliam** [dani8art/docker-manager-npm#22]
I'm trying to use `--abort-on-container-exit` option and can't because -d is hard coded as default option in https://github.com/dani8art/docker-compose-manager/blob/master/src/docker-compose-manager.js#L93

**Comment by dani8art** [comment]
Hi @renanwilliam,
It's true. I will remove and release a new version 0.1.1 to fix this issue. Thank you.

**Comment by dani8art** [comment]
hi @renanwilliam, finally, you have the feature on version [v0.1.2](https://www.npmjs.com/package/docker-composer-manager), thank you very much!
